name: E2e test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  neo4j_test:
    name: Run all tests using Docker/Neo4j
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version
      - name: Docker compose
        run: docker-compose up --wait
      - name: Install npm dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Run all the tests
        run: npm test
      - name: Send coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
